// JavaScript Document

document.writeln("<div class=\"jxService clearfix\">");
document.writeln("                <div class=\"jxbg\">");
document.writeln("                    <a class=\"jxClose\">关闭</a>");
document.writeln("                    <div class=\"changeCon\">");
document.writeln("                        <div>");
document.writeln("                        	<dl class=\"serTit\">");
document.writeln("                                <dt>学而思培优服务中心</dt>");
document.writeln("                                <dd>");
document.writeln("                                    <p class=\"tel\"><em>报名咨询</em> <b>010-82618899 62164116</b></p>");
document.writeln("                                    <p>（专线咨询时间：周一至周日8：00—21：00）</p>");
document.writeln("                                </dd>");
document.writeln("                            </dl>");
document.writeln("                            <div class=\"clearfix topMargin15 border jxTab\">");
document.writeln("                                <ul class=\"jxTit\">");
document.writeln("                                    <li class=\"jxOn\">海淀区</li>");
document.writeln("                                    <li>朝阳区</li>");
document.writeln("                                    <li>西城区</li>");
document.writeln("                                    <li>东城区</li>");
document.writeln("                                    <li>石景山区</li>");
document.writeln("                                    <li>丰台区</li>");
document.writeln("                                    <li>昌平区</li>");
document.writeln("                                    <li>顺义区</li>");
document.writeln("                                    <li>房山区</li>");
document.writeln("                                    <li>通州区</li>");
document.writeln("                                    <li>大兴区</li>");
document.writeln("                                </ul>");
document.writeln("                                <div class=\"jxCon clearfix\">");
document.writeln("                                    <div>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">82772361</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#shangdi\" target=\"_blank\">上地</a></li>");
document.writeln("                                            <li><em class=\"right\">82050281</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#zhichunlu\" target=\"_blank\">知春路</a></li>");
document.writeln("                                            <li><em class=\"right\">82628869</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#wudaokou\" target=\"_blank\">五道口</a></li>");
document.writeln("                                            <li><em class=\"right\">62160967</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#dazhongsi\" target=\"_blank\">大钟寺</a></li>");
document.writeln("                                            <li><em class=\"right\">51733791</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#6daokou\" target=\"_blank\">六道口</a></li>");
document.writeln("                                            <li><em class=\"right\">82038011</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#zhixinqiao1\" target=\"_blank\">志新桥</a></li>");
document.writeln("                                            <li><em class=\"right\">68154561</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#gongzhufen\" target=\"_blank\">翠微路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">58819078</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#wanliu\" target=\"_blank\">万柳</a></li>");
document.writeln("                                            <li><em class=\"right\">68484083</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#zizhuqiao\" target=\"_blank\">紫竹桥</a></li>");
document.writeln("                                            <li><em class=\"right\">62148821</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#weigongcun\" target=\"_blank\">魏公村</a></li>");
document.writeln("                                            <li><em class=\"right\">88029236</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#baishiqiao\" target=\"_blank\">白石桥</a></li>");
document.writeln("                                            <li><em class=\"right\">68983115</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#hangtianqiao\" target=\"_blank\">航天桥</a></li>");
document.writeln("                                            <li><em class=\"right\">68352008</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#ganjiakou\" target=\"_blank\">甘家口</a></li>");
document.writeln("                                            <li><em class=\"right\">68218921</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#yuquanlu\" target=\"_blank\">玉泉路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">88865789</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#jinyuan\" target=\"_blank\">金源时代</a></li>");
document.writeln("                                            <li><em class=\"right\">52926728</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#hesheng\" target=\"_blank\">海淀黄庄</a></li>");
document.writeln("                                            <li><em class=\"right\">82044172</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#jinmenqiao\" target=\"_blank\">蓟门桥东</a></li>");
document.writeln("                                            <li><em class=\"right\">63952135</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#gzfn\" target=\"_blank\">公主坟南</a></li>");
document.writeln("                                            <li><em class=\"right\">62915903</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#qinghe\" target=\"_blank\">清河小营</a></li>");
document.writeln("                                            <li><em class=\"right\">62573662</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#zhichunli\" target=\"_blank\">科学院南路</a></li>");
document.writeln("                                            <li><em class=\"right\">82617670</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#zhongguancun\" target=\"_blank\">海淀图书城</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">58872900</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#tiancunlu\" target=\"_blank\">田村</a></li>");
document.writeln("                                            <li><em class=\"right\">88456167</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#yuandalu\" target=\"_blank\">远大路</a></li>");
document.writeln("                                            <li><em class=\"right\">88430433</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#ldc\" target=\"_blank\">蓝靛厂</a></li>");
document.writeln("                                            <li><em class=\"right\">68298236</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#chengxiang\" target=\"_blank\">公主坟城乡</a></li>");
document.writeln("                                            <li><em class=\"right\">52858232</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#gzfqyw\" target=\"_blank\">公主坟企业网</a></li>");
document.writeln("                                            <li><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#zhongkun\" target=\"_blank\">摩比思维-中坤馆</a></li>");
document.writeln("                                            <li><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#mbsjinyuan\" target=\"_blank\">摩比思维-金源时代</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">59627166</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#jinsong\" target=\"_blank\">劲松</a></li>");
document.writeln("                                            <li><em class=\"right\">87760291</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#guangql\" target=\"_blank\">双井</a></li>");
document.writeln("                                            <li><em class=\"right\">65918819</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#tuanjiehu\" target=\"_blank\">团结湖</a></li>");
document.writeln("                                            <li><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#aoya\" target=\"_blank\">摩比思维-亚运村</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">64402967</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#hepingli1\" target=\"_blank\">柳芳</a></li>");
document.writeln("                                            <li><em class=\"right\">85628402</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#chaowai\" target=\"_blank\">朝外</a></li>");
document.writeln("                                            <li><em class=\"right\">64929030</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#yayuncun1\" target=\"_blank\">亚运村</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">51368154</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#caimanjie\" target=\"_blank\">财满街</a></li>");
document.writeln("                                            <li><em class=\"right\">85852075</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#shilipu\" target=\"_blank\">十里堡</a></li>");
document.writeln("                                            <li><em class=\"right\">64423090</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#anzhenli\" target=\"_blank\">安贞桥西</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">65797152</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#cyljdy\" target=\"_blank\">管庄</a></li>");
document.writeln("                                            <li><em class=\"right\">84888010</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#yayuncun\" target=\"_blank\">惠新东桥</a></li>");
document.writeln("                                            <li><em class=\"right\">64713288</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#wangjinghuyuan\" target=\"_blank\">望京花园</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">68005032</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#fuchengmen\" target=\"_blank\">阜成门</a></li>");
document.writeln("                                            <li><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#caibai\" target=\"_blank\">摩比思维-菜百</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">66551739</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#sizhong\" target=\"_blank\">平安里</a></li>");
document.writeln("                                            <li><em class=\"right\">63512501</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#baizhifang\" target=\"_blank\">白纸坊</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">63182986</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#hepingmen1\" target=\"_blank\">和平门</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">51816365</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#xuanwucaibai\" target=\"_blank\">宣武菜百</a></li>");
document.writeln("                                            <li><em class=\"right\">51379086</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#honglnl\" target=\"_blank\">红莲南路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">65120785</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#dengshikou\" target=\"_blank\">灯市口</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">87103892</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#guangqumen\" target=\"_blank\">广渠门</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">52186466</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#xinzhongjie\" target=\"_blank\">新中街</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">64171083</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#dongsi\" target=\"_blank\">东四十条(原张自忠路)</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">68865319</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#zhongyan\" target=\"_blank\">八角</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">68865546</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#yangzhuang\" target=\"_blank\">杨庄</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">88692768</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#lugl\" target=\"_blank\">鲁谷路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">88778835</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#jindingjie\" target=\"_blank\">金顶街</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">67643258</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#fangzhuang\" target=\"_blank\">方庄</a></li>");
document.writeln("                                            <li><em class=\"right\">67612797</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#puhuangyu\" target=\"_blank\">蒲黄榆</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">88539808</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#yungang\" target=\"_blank\">云岗</a></li>");
document.writeln("                                            <li><em class=\"right\">87562745</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#soubaoshangwuzhongxin\" target=\"_blank\">马家堡</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">67063735</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#donggaodi\" target=\"_blank\">东高地</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">51039177</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#beidadi\" target=\"_blank\">北大地</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">59812457</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#huilongguan\" target=\"_blank\">回龙观</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">64113351</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#tty\" target=\"_blank\">天通苑</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">51429055</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#donghl\" target=\"_blank\">昌平东环路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">57347769</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#shunyi\" target=\"_blank\">站前东街</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">69360320</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#liangxiang\" target=\"_blank\">良乡</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">81524243</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#9keshu\" target=\"_blank\">九棵树</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">67890521</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#yizhuang\" target=\"_blank\">亦庄</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">60211382</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#huoshenmiao\" target=\"_blank\">火神庙</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");