// JavaScript Document

document.writeln("<div class=\"jxService clearfix\">");
document.writeln("                <div class=\"jxbg\">");
document.writeln("                    <ul class=\"changeTit changeTit1 ft14 bold white\">");
document.writeln("                        <li class=\"changeOn changeOn1\">北京</li>");
document.writeln("                        <li>上海</li>");
document.writeln("                        <li>天津</li>");
document.writeln("                        <li>广州</li>");
document.writeln("                        <li>深圳</li>");
document.writeln("                        <li>武汉</li>");
document.writeln("                        <li>南京</li>");
document.writeln("                        <li>杭州</li>");
document.writeln("                        <li>成都</li>");
document.writeln("                        <li>西安</li>");
document.writeln("                    </ul>");
document.writeln("                    <a class=\"jxClose\">关闭</a>");
document.writeln("                    <div class=\"changeCon changeCon1\">");
document.writeln("                        <div>");
document.writeln("                        	<dl class=\"serTit\">");
document.writeln("                                <dt>学而思培优服务中心</dt>");
document.writeln("                                <dd>");
document.writeln("                                    <p class=\"tel\"><em>报名咨询</em> <b>010-82618899 62164116</b></p>");
document.writeln("                                    <p>（专线咨询时间：周一至周日8：00—21：00）</p>");
document.writeln("                                </dd>");
document.writeln("                            </dl>");
document.writeln("                            <div class=\"clearfix topMargin15 border jxTab\">");
document.writeln("                                <ul class=\"jxTit jxTit1\">");
document.writeln("                                    <li class=\"jxOn jxOn1\">海淀区</li>");
document.writeln("                                    <li>朝阳区</li>");
document.writeln("                                    <li>西城区</li>");
document.writeln("                                    <li>东城区</li>");
document.writeln("                                    <li>石景山区</li>");
document.writeln("                                    <li>丰台区</li>");
document.writeln("                                    <li>昌平区</li>");
document.writeln("                                    <li>顺义区</li>");
document.writeln("                                    <li>房山区</li>");
document.writeln("                                    <li>通州区</li>");
document.writeln("                                    <li>大兴区</li>");
document.writeln("                                </ul>");
document.writeln("                                <div class=\"jxCon jxCon1 clearfix\">");
document.writeln("                                    <div>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">82772361</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#shangdi\" target=\"_blank\">上地</a></li>");
document.writeln("                                            <li><em class=\"right\">82050281</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#zhichunlu\" target=\"_blank\">知春路</a></li>");
document.writeln("                                            <li><em class=\"right\">82628869</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#wudaokou\" target=\"_blank\">五道口</a></li>");
document.writeln("                                            <li><em class=\"right\">62160967</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#dazhongsi\" target=\"_blank\">大钟寺</a></li>");
document.writeln("                                            <li><em class=\"right\">51733791</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#6daokou\" target=\"_blank\">六道口</a></li>");
document.writeln("                                            <li><em class=\"right\">82038011</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#zhixinqiao1\" target=\"_blank\">志新桥</a></li>");
document.writeln("                                            <li><em class=\"right\">68154561</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#gongzhufen\" target=\"_blank\">翠微路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">58819078</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#wanliu\" target=\"_blank\">万柳</a></li>");
document.writeln("                                            <li><em class=\"right\">68484083</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#zizhuqiao\" target=\"_blank\">紫竹桥</a></li>");
document.writeln("                                            <li><em class=\"right\">62148821</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#weigongcun\" target=\"_blank\">魏公村</a></li>");
document.writeln("                                            <li><em class=\"right\">88029236</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#baishiqiao\" target=\"_blank\">白石桥</a></li>");
document.writeln("                                            <li><em class=\"right\">68983115</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#hangtianqiao\" target=\"_blank\">航天桥</a></li>");
document.writeln("                                            <li><em class=\"right\">68352008</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#ganjiakou\" target=\"_blank\">甘家口</a></li>");
document.writeln("                                            <li><em class=\"right\">68218921</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#yuquanlu\" target=\"_blank\">玉泉路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">88865789</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#jinyuan\" target=\"_blank\">金源时代</a></li>");
document.writeln("                                            <li><em class=\"right\">52926728</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#hesheng\" target=\"_blank\">海淀黄庄</a></li>");
document.writeln("                                            <li><em class=\"right\">82044172</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#jinmenqiao\" target=\"_blank\">蓟门桥东</a></li>");
document.writeln("                                            <li><em class=\"right\">63952135</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#gzfn\" target=\"_blank\">公主坟南</a></li>");
document.writeln("                                            <li><em class=\"right\">62915903</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#qinghe\" target=\"_blank\">清河小营</a></li>");
document.writeln("                                            <li><em class=\"right\">62573662</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#zhichunli\" target=\"_blank\">科学院南路</a></li>");
document.writeln("                                            <li><em class=\"right\">82617670</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#zhongguancun\" target=\"_blank\">海淀图书城</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">58872900</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#tiancunlu\" target=\"_blank\">田村</a></li>");
document.writeln("                                            <li><em class=\"right\">88456167</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#yuandalu\" target=\"_blank\">远大路</a></li>");
document.writeln("                                            <li><em class=\"right\">88430433</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#ldc\" target=\"_blank\">蓝靛厂</a></li>");
document.writeln("                                            <li><em class=\"right\">68298236</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#chengxiang\" target=\"_blank\">公主坟城乡</a></li>");
document.writeln("                                            <li><em class=\"right\">52858232</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#gzfqyw\" target=\"_blank\">公主坟企业网</a></li>");
document.writeln("                                            <li><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#zhongkun\" target=\"_blank\">摩比思维-中坤馆</a></li>");
document.writeln("                                            <li><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#mbsjinyuan\" target=\"_blank\">摩比思维-金源时代</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">59627166</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#jinsong\" target=\"_blank\">劲松</a></li>");
document.writeln("                                            <li><em class=\"right\">87760291</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#guangql\" target=\"_blank\">双井</a></li>");
document.writeln("                                            <li><em class=\"right\">65918819</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#tuanjiehu\" target=\"_blank\">团结湖</a></li>");
document.writeln("                                            <li><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#aoya\" target=\"_blank\">摩比思维-亚运村</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">64402967</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#hepingli1\" target=\"_blank\">柳芳</a></li>");
document.writeln("                                            <li><em class=\"right\">85628402</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#chaowai\" target=\"_blank\">朝外</a></li>");
document.writeln("                                            <li><em class=\"right\">64929030</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#yayuncun1\" target=\"_blank\">亚运村</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">51368154</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#caimanjie\" target=\"_blank\">财满街</a></li>");
document.writeln("                                            <li><em class=\"right\">85852075</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#shilipu\" target=\"_blank\">十里堡</a></li>");
document.writeln("                                            <li><em class=\"right\">64423090</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#anzhenli\" target=\"_blank\">安贞桥西</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">65797152</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#cyljdy\" target=\"_blank\">管庄</a></li>");
document.writeln("                                            <li><em class=\"right\">84888010</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#yayuncun\" target=\"_blank\">惠新东桥</a></li>");
document.writeln("                                            <li><em class=\"right\">64713288</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#wangjinghuyuan\" target=\"_blank\">望京花园</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">68005032</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#fuchengmen\" target=\"_blank\">阜成门</a></li>");
document.writeln("                                            <li><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#caibai\" target=\"_blank\">摩比思维-菜百</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">66551739</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#sizhong\" target=\"_blank\">平安里</a></li>");
document.writeln("                                            <li><em class=\"right\">63512501</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#baizhifang\" target=\"_blank\">白纸坊</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">63182986</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#hepingmen1\" target=\"_blank\">和平门</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">51816365</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#xuanwucaibai\" target=\"_blank\">宣武菜百</a></li>");
document.writeln("                                            <li><em class=\"right\">51379086</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#honglnl\" target=\"_blank\">红莲南路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">65120785</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#dengshikou\" target=\"_blank\">灯市口</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">87103892</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#guangqumen\" target=\"_blank\">广渠门</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">52186466</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#xinzhongjie\" target=\"_blank\">新中街</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">64171083</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#dongsi\" target=\"_blank\">东四十条(原张自忠路)</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">68865319</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#zhongyan\" target=\"_blank\">八角</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">68865546</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#yangzhuang\" target=\"_blank\">杨庄</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">88692768</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#lugl\" target=\"_blank\">鲁谷路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">88778835</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#jindingjie\" target=\"_blank\">金顶街</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">56421995</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#fangzhuang\" target=\"_blank\">方庄</a></li>");
document.writeln("                                            <li><em class=\"right\">67612797</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#puhuangyu\" target=\"_blank\">蒲黄榆</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">88539808</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#yungang\" target=\"_blank\">云岗</a></li>");
document.writeln("                                            <li><em class=\"right\">87562745</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#soubaoshangwuzhongxin\" target=\"_blank\">马家堡</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">67063735</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#donggaodi\" target=\"_blank\">东高地</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">51039177</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#beidadi\" target=\"_blank\">北大地</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">59812457</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#huilongguan\" target=\"_blank\">回龙观</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">64113351</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#tty\" target=\"_blank\">天通苑</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">51429055</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#donghl\" target=\"_blank\">昌平东环路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">57347769</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#shunyi\" target=\"_blank\">站前东街</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">69360320</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#liangxiang\" target=\"_blank\">良乡</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">81524243</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#9keshu\" target=\"_blank\">九棵树</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">67890521</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#yizhuang\" target=\"_blank\">亦庄</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">60211382</em><a href=\"http://bj.speiyou.com/z2012/fuwuzhongxin/index.html#huoshenmiao\" target=\"_blank\">火神庙</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"divNone\">");
document.writeln("                        	<dl class=\"serTit\">");
document.writeln("                                <dt>学而思培优服务中心</dt>");
document.writeln("                                <dd>");
document.writeln("                                    <p class=\"tel\"><em>报名咨询</em> <b>021-32159666</b></p>");
document.writeln("                                    <p>（专线咨询时间：周一至周日8：00—21：00）</p>");
document.writeln("                                </dd>");
document.writeln("                            </dl>");
document.writeln("                            <div class=\"clearfix topMargin15 border jxTab\">");
document.writeln("                                <ul class=\"jxTit jxTit1\">");
document.writeln("                                    <li class=\"jxOn jxOn1\">闵行区</li>");
document.writeln("                                    <li>徐汇区</li>");
document.writeln("                                    <li>虹口区</li>");
document.writeln("                                    <li>黄浦区</li>");
document.writeln("                                    <li>长宁区</li>");
document.writeln("                                    <li>杨浦区</li>");
document.writeln("                                    <li>浦东新区</li>");
document.writeln("                                    <li>闸北区</li>");
document.writeln("                                    <li>普陀区</li>");
document.writeln("                                    <li>卢湾区</li>");
document.writeln("                                </ul>");
document.writeln("                                <div class=\"jxCon jxCon1 clearfix\">");
document.writeln("                                    <div>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">64611463</em><a href=\"http://sh.aoshu.com/z2010/address/address/qibao.html\" target=\"_blank\">七莘路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">54811477</em><a href=\"http://sh.aoshu.com/z2010/address/address/meilong.html\" target=\"_blank\">莲花路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">34224473</em><a href=\"http://sh.aoshu.com/z2010/address/address/pingyang.html\" target=\"_blank\">平阳路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">34224473</em><a href=\"http://sh.aoshu.com/z2010/address/address/gumei.html\" target=\"_blank\">顾戴路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">64042876</em><a href=\"http://sh.aoshu.com/z2010/address/address/xuhui.html\" target=\"_blank\">大木桥路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">64759885</em><a href=\"http://sh.aoshu.com/z2010/address/address/tianlin.html\" target=\"_blank\">田林路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">54042831</em><a href=\"http://sh.aoshu.com/z2010/address/address/guiping.html\" target=\"_blank\">桂平路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">36352263</em><a href=\"http://sh.aoshu.com/z2010/address/address/sichuan.html\" target=\"_blank\">四川北路</a></li>                                   ");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">36368177</em><a href=\"http://sh.aoshu.com/z2010/address/address/huayuan.html#dong\" target=\"_blank\">东江湾路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">33627917</em><a href=\"http://sh.aoshu.com/z2010/address/address/huayuan.html\" target=\"_blank\">花园路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                             <li><em class=\"right\">65018060</em><a href=\"http://sh.aoshu.com/z2010/address/address/quyang.html\" target=\"_blank\">曲阳路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">33310535</em><a href=\"http://sh.aoshu.com/z2010/address/address/huangpu.html\" target=\"_blank\">宁海东路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">63506271</em><a href=\"http://sh.aoshu.com/z2010/address/address/huangpu.html\" target=\"_blank\">北海路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">63506271</em><a href=\"http://sh.aoshu.com/z2010/address/address/huangpu.html\" target=\"_blank\">汉口路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">32502057</em><a href=\"http://sh.aoshu.com/z2010/address/address/changning.html\" target=\"_blank\">天山路（近中山西路）</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">62336782</em><a href=\"http://sh.aoshu.com/z2010/address/address/changning2.html\" target=\"_blank\">芙蓉江路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">32525154</em><a href=\"http://sh.aoshu.com/z2010/address/address/beixinjing.html\" target=\"_blank\">北渔路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">35121522</em><a href=\"http://sh.aoshu.com/z2010/address/address/yangpu.html\" target=\"_blank\">大连路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">55091072</em><a href=\"http://sh.aoshu.com/z2010/address/address/siping.html\" target=\"_blank\">四平路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">64608375</em><a href=\"http://sh.aoshu.com/z2010/address/address/changyang.html\" target=\"_blank\">长阳路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">20286758</em><a href=\"http://sh.aoshu.com/z2010/address/address/pudongnan.html\" target=\"_blank\">浦东南路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">68762732</em><a href=\"http://sh.aoshu.com/z2010/address/address/dongfang.html\" target=\"_blank\">东方路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">36531737</em><a href=\"http://sh.aoshu.com/z2010/address/address/jiangchang.html\" target=\"_blank\">江场西路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">52666771</em><a href=\"http://sh.aoshu.com/z2010/address/address/meichuan.html\" target=\"_blank\">梅川路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">33317881</em><a href=\"http://sh.aoshu.com/z2010/address/address/xietu.html\" target=\"_blank\">斜土路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"divNone\">");
document.writeln("                        	<dl class=\"serTit\">");
document.writeln("                                <dt>学而思培优服务中心</dt>");
document.writeln("                                <dd>");
document.writeln("                                    <p class=\"tel\"><em>报名咨询</em> <b>022-83310282</b></p>");
document.writeln("                                    <p>（专线咨询时间：周一至周日8：00—21：00）</p>");
document.writeln("                                </dd>");
document.writeln("                            </dl>");
document.writeln("                            <div class=\"clearfix topMargin15 border jxTab\">");
document.writeln("                                <ul class=\"jxTit jxTit1\">");
document.writeln("                                    <li class=\"jxOn jxOn1\">和平区</li>");
document.writeln("                                    <li>南开区</li>");
document.writeln("                                    <li>河西区</li>");
document.writeln("                                    <li>河北区</li>");
document.writeln("                                </ul>");
document.writeln("                                <div class=\"jxCon jxCon1 clearfix\">");
document.writeln("                                    <div>");
document.writeln("                                        <ul class=\"jx_sz col4f\">");
document.writeln("                                            <li><em class=\"right\">022-27304563</em><a href=\"http://tj.aoshu.com/200808/492fcbc8bee9c.shtml\" target=\"_blank\">河川</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"jx_sz col4f\">");
document.writeln("                                            <li><em class=\"right\">022-27232153</em><a href=\"http://tj.aoshu.com/e/20110628/4e0983358d6e8.shtml\" target=\"_blank\">经联大厦</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"jx_sz col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">022-23116607</em><a href=\"http://tj.aoshu.com/e/20110511/4dca5e2ac8bb0.shtml\" target=\"_blank\">烟台道</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"jx_sz col4f\">");
document.writeln("                                            <li><a href=\"http://tj.aoshu.com/200809/492fcb81b8817.shtml\" target=\"_blank\">华苑第二教学点</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"jx_sz col4f\">");
document.writeln("                                            <li><em class=\"right\">022-87520336</em><a href=\"http://tj.aoshu.com/e/20101221/4d10240e972ed.shtml\" target=\"_blank\">长江道</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"jx_sz col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">022-23720027</em><a href=\"http://tj.aoshu.com/200809/492fcb81b8817.shtml\" target=\"_blank\">华苑</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"jx_sz col4f\">");
document.writeln("                                            <li><em class=\"right\">022-23391269</em><a href=\"http://tj.aoshu.com/200912/4b2d7d8099a6c.shtml\" target=\"_blank\">小白楼</a></li>                                   ");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"jx_sz col4f\">");
document.writeln("                                            <li><em class=\"right\">022-28263892</em><a href=\"http://tj.aoshu.com/e/20110208/4d50b7af1ee6f.shtml\" target=\"_blank\">南楼</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\"divNone\">");
document.writeln("                                        <ul class=\"jx_sz col4f\">");
document.writeln("                                            <li><em class=\"right\">022-26210962</em><a href=\"http://tj.aoshu.com/e/20110325/4d8c5d1538111.shtml\" target=\"_blank\">中山路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"divNone\">");
document.writeln("                        	<dl class=\"serTit\">");
document.writeln("                                <dt>学而思培优服务中心</dt>");
document.writeln("                                <dd>");
document.writeln("                                    <p class=\"tel\"><em>报名咨询</em> <b>020-22891616</b></p>");
document.writeln("                                    <p>专线咨询时间：周一到周四：8:00-19:00，</p>");
document.writeln("                                    <p>周五到周日：8:00-21:00</p>");
document.writeln("                                </dd>");
document.writeln("                            </dl>");
document.writeln("                            <div class=\"clearfix topMargin15 border jxTab\">");
document.writeln("                                <div class=\"jxCon jxCon1 clearfix\">");
document.writeln("                                    <div>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">020-87597745</em><a href=\"http://gz.aoshu.com/z2012/fwzxjs/index.html\" target=\"_blank\">岗顶</a></li>");
document.writeln("                                            <li><em class=\"right\">020-87385400</em><a href=\"http://gz.aoshu.com/z2012/fwzxjs/index3.html\" target=\"_blank\">杨箕</a></li>");
document.writeln("                                             <li><em class=\"right\">020-86527171</em><a href=\"http://gz.aoshu.com/z2012/fwzxjs/index8.html\" target=\"_blank\">西村</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">020-87590203</em><a href=\"http://gz.aoshu.com/z2012/fwzxjs/index2.html\" target=\"_blank\">新岗顶</a></li>");
document.writeln("                                            <li><em class=\"right\">020-22050515</em><a href=\"http://gz.aoshu.com/z2012/fwzxjs/index6.html\" target=\"_blank\">动物园</a></li>");
document.writeln("                                            <li><em class=\"right\">020-22050515</em><a href=\"http://gz.aoshu.com/z2012/fwzxjs/index10.html\" target=\"_blank\">小北</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">020-87750200</em><a href=\"http://gz.aoshu.com/z2012/fwzxjs/index5.html\" target=\"_blank\">区庄</a></li>");
document.writeln("                                            <li><em class=\"right\">020-83827123</em><a href=\"http://gz.aoshu.com/z2012/fwzxjs/index9.html\" target=\"_blank\">淘金</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">020-83750520</em><a href=\"http://gz.aoshu.com/z2012/fwzxjs/index4.html\" target=\"_blank\">烈士陵园</a></li>");
document.writeln("                                            <li><em class=\"right\">020-22050601</em><a href=\"http://gz.aoshu.com/z2012/fwzxjs/index7.html\" target=\"_blank\">农讲所</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"divNone\">");
document.writeln("                        	<dl class=\"serTit\">");
document.writeln("                                <dt>学而思培优服务中心</dt>");
document.writeln("                                <dd>");
document.writeln("                                    <p class=\"tel\"><em>报名咨询</em> <b>0755-61863366</b></p>");
document.writeln("                                    <p>（专线咨询时间：周一至周日：9:00——19:00）</p>");
document.writeln("                                </dd>");
document.writeln("                            </dl>");
document.writeln("                            <div class=\"clearfix topMargin15 border jxTab\">");
document.writeln("                                <div class=\"jxCon jxCon1 clearfix\">");
document.writeln("                                    <div>");
document.writeln("                                        <ul class=\"jx_sz col4f\">");
document.writeln("                                            <li><em class=\"right\">33358625/33358626</em><a href=\"http://sz.aoshu.com/include/xiangmihu_fwzx.html\" target=\"_blank\">香蜜湖校区</a></li>");
document.writeln("                                            <li><em class=\"right\">83865882/83865883</em><a href=\"http://sz.aoshu.com/include/jingtian_fwzx.html\" target=\"_blank\">景田银座</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"jx_sz col4f\">");
document.writeln("                                            <li><em class=\"right\">22250661/22250662</em><a href=\"http://sz.aoshu.com/include/dongle_fwzx.html\" target=\"_blank\">东湖百仕达</a></li>");
document.writeln("                                            <li><em class=\"right\">61355991/61355992</em><a href=\"http://sz.aoshu.com/include/index_fwzx.html\" target=\"_blank\">红荔上步</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"jx_sz col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">26888846/26888847</em><a href=\"http://sz.aoshu.com/include/nanshan_fwzx.html\" target=\"_blank\">南海花园城</a></li>");
document.writeln("                                            <li><em class=\"right\">22651584/22312340</em><a href=\"http://sz.aoshu.com/include/cuizhu.html\" target=\"_blank\">翠竹</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"jx_sz col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">83941155/83942255</em><a href=\"http://sz.aoshu.com/include/nanshan_fwzx.html\" target=\"_blank\">益田石厦</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>                            ");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"divNone\">");
document.writeln("                        	<dl class=\"serTit\">");
document.writeln("                                <dt>学而思培优服务中心</dt>");
document.writeln("                                <dd>");
document.writeln("                                    <p class=\"tel\"><em>报名咨询</em> <b>4006-566-196</b></p>");
document.writeln("                                    <p>（专线咨询时间：周一至周日8：00—19：00）</p>");
document.writeln("                                </dd>");
document.writeln("                            </dl>");
document.writeln("                            <div class=\"clearfix topMargin15 border jxTab\">");
document.writeln("                                <div class=\"jxCon jxCon1 clearfix\">");
document.writeln("                                    <div>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">027-85723332</em><a href=\"http://wh.aoshu.com/z/address/address/qushuilou.html\" target=\"_blank\">取水楼</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">027-65691849</em><a href=\"http://wh.aoshu.com/z/address/address/yangchahu.html\" target=\"_blank\">杨汊湖</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">027-82624855</em><a href=\"http://wh.aoshu.com/z/address/address/huaiqiao.html\" target=\"_blank\">花桥</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">027-87716307</em><a href=\"http://wh.aoshu.com/z/address/address/wululu.html\" target=\"_blank\">武昌</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"divNone\">");
document.writeln("                        	<dl class=\"serTit\">");
document.writeln("                                <dt>学而思培优服务中心</dt>");
document.writeln("                                <dd>");
document.writeln("                                    <p class=\"tel\"><em>报名咨询</em> <b>4006-566-196</b></p>");
document.writeln("                                    <p>（专线咨询时间：周一至周日8：00—19：00）</p>");
document.writeln("                                </dd>");
document.writeln("                            </dl>");
document.writeln("                            <div class=\"clearfix topMargin15 border jxTab\">");
document.writeln("                                <div class=\"jxCon jxCon1 clearfix\">");
document.writeln("                                    <div>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">025-52857400</em><a href=\"http://nj.aoshu.com/z2011/sxl/index.shtml\" target=\"_blank\">山西路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">025-52857240</em><a href=\"http://nj.aoshu.com/z2011/ljl/index.shtml\" target=\"_blank\">漓江路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f\">");
document.writeln("                                            <li><em class=\"right\">025-52857241</em><a href=\"http://nj.aoshu.com/z2011/lp/index.shtml\" target=\"_blank\">龙蟠中路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">025-52857140</em><a href=\"http://nj.aoshu.com/z2013/gl/index.shtml\" target=\"_blank\">鼓楼</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"divNone\">");
document.writeln("                        	<dl class=\"serTit\">");
document.writeln("                                <dt>学而思培优服务中心</dt>");
document.writeln("                                <dd>");
document.writeln("                                    <p class=\"tel\"><em>报名咨询</em> <b>4006-566-196</b></p>");
document.writeln("                                    <p>（专线咨询时间：周一至周日8：00—19：00）</p>");
document.writeln("                                </dd>");
document.writeln("                            </dl>");
document.writeln("                            <div class=\"clearfix topMargin15 border jxTab\">");
document.writeln("                                <div class=\"jxCon jxCon1 clearfix\">");
document.writeln("                                    <ul class=\"jx_sz col4f\">");
document.writeln("                                        <li><em class=\"right\">0571—88868153</em><a href=\"http://hz.aoshu.com/e/20110712/4e1c2acde79bd.shtml\" target=\"_blank\">文二路</a></li>");
document.writeln("                                    </ul>");
document.writeln("                                    <ul class=\"jx_sz col4f\">");
document.writeln("                                        <li><em class=\"right\">0571-86715305</em><a href=\"http://hz.aoshu.com/e/20110712/4e1c2c389a565.shtml\" target=\"_blank\">新华路</a></li>");
document.writeln("                                    </ul>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"divNone\">");
document.writeln("                        	<dl class=\"serTit\">");
document.writeln("                                <dt>学而思培优服务中心</dt>");
document.writeln("                                <dd>");
document.writeln("                                    <p class=\"tel\"><em>报名咨询</em> <b>4006-566-196</b></p>");
document.writeln("                                    <p>（专线咨询时间：周一至周日8：00—19：00）</p>");
document.writeln("                                </dd>");
document.writeln("                            </dl>");
document.writeln("                            <div class=\"clearfix topMargin15 border jxTab\">");
document.writeln("                                <div class=\"jxCon clearfix\">");
document.writeln("                                    <ul class=\"jx_sz col4f\">");
document.writeln("                                        <li><em class=\"right\">028-61368705</em><a href=\"http://cd.zhongkao.com/e/20110819/4e4df3d9470f1.shtml\" target=\"_blank\">西门嘉园大厦</a></li>");
document.writeln("                                    </ul>");
document.writeln("                                    <ul class=\"jx_sz col4f\">");
document.writeln("                                        <li><em class=\"right\">028-85513391</em><a href=\"http://cd.aoshu.com/e/20110414/4da68eb48be94.shtml\" target=\"_blank\">文翁路</a></li>");
document.writeln("                                    </ul>");
document.writeln("                                    <ul class=\"jx_sz col4f noMargin\">");
document.writeln("                                        <li><em class=\"right\">028-86133391</em><a href=\"http://cd.zhongkao.com/e/20110714/4e1e65e129b48.shtml\" target=\"_blank\">肖家河</a></li>");
document.writeln("                                    </ul>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"divNone\">");
document.writeln("                        	<dl class=\"serTit\">");
document.writeln("                                <dt>学而思培优服务中心</dt>");
document.writeln("                                <dd>");
document.writeln("                                    <p class=\"tel\"><em>报名咨询</em> <b>4006-566-196</b></p>");
document.writeln("                                    <p>（专线咨询时间：周一至周日8：00—19：00）</p>");
document.writeln("                                </dd>");
document.writeln("                            </dl>");
document.writeln("                            <div class=\"clearfix topMargin15 border jxTab\">");
document.writeln("                                <div class=\"jxCon clearfix\">");
document.writeln("                                    <div>");
document.writeln("                                        <ul class=\"jx_sz col4f\">");
document.writeln("                                            <li><em class=\"right\">029-88243766</em><a href=\"http://xa.aoshu.com/z2012/kjl/index.htm\" target=\"_blank\">高新科技路</a></li>");
document.writeln("                                            <li><em class=\"right\">029-88600682</em><a href=\"http://xa.aoshu.com/z2012/kcl/index3.htm\" target=\"_blank\">高新科创路</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"jx_sz col4f\">");
document.writeln("                                            <li><em class=\"right\">029-82220478</em><a href=\"http://xa.aoshu.com/z2012/yfds/index2.htm\" target=\"_blank\">东郊云峰大厦</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                        <ul class=\"jx_sz col4f noMargin\">");
document.writeln("                                            <li><em class=\"right\">029-89193986</em><a href=\"http://xa.aoshu.com/z2012/mjq/index1.htm\" target=\"_blank\">高新糜家桥</a></li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");