/*! Copyright 2013 Baidu Inc. All RightsReserved. */;(function(){var baidu=(function(){var T,baidu=T=baidu||{version:"1.5.2"};baidu.guid="$BAIDU$";baidu.$$=window[baidu.guid]=window[baidu.guid]||{global:{}};baidu.dom=baidu.dom||{};baidu.dom.g=function(a){if(!a){return null}if("string"==typeof a||a instanceof String){return document.getElementById(a)}else{if(a.nodeName&&(a.nodeType==1||a.nodeType==9)){return a}}return null};baidu.g=baidu.G=baidu.dom.g;baidu.dom._styleFixer=baidu.dom._styleFixer||{};baidu.dom._styleFilter=baidu.dom._styleFilter||[];baidu.dom._styleFilter.filter=function(b,e,f){for(var a=0,d=baidu.dom._styleFilter,c;c=d[a];a++){if(c=c[f]){e=c(b,e)}}return e};baidu.string=baidu.string||{};baidu.string.toCamelCase=function(a){if(a.indexOf("-")<0&&a.indexOf("_")<0){return a}return a.replace(/[-_][^-_]/g,function(b){return b.charAt(1).toUpperCase()})};baidu.dom.setStyle=function(c,b,d){var e=baidu.dom,a;
c=e.g(c);b=baidu.string.toCamelCase(b);if(a=e._styleFilter){d=a.filter(b,d,"set")}a=e._styleFixer[b];(a&&a.set)?a.set(c,d):(c.style[a||b]=d);return c};baidu.setStyle=baidu.dom.setStyle;baidu.dom.setStyles=function(b,c){b=baidu.dom.g(b);for(var a in c){baidu.dom.setStyle(b,a,c[a])}return b};baidu.setStyles=baidu.dom.setStyles;baidu.browser=baidu.browser||{};(function(){var a=navigator.userAgent;baidu.browser.safari=/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(a)&&!/chrome/i.test(a)?+(RegExp["\x241"]||RegExp["\x242"]):undefined})();baidu.browser.ie=baidu.ie=/msie (\d+\.\d+)/i.test(navigator.userAgent)?(document.documentMode||+RegExp["\x241"]):undefined;baidu.browser.opera=/opera(\/| )(\d+(\.\d+)?)(.+?(version\/(\d+(\.\d+)?)))?/i.test(navigator.userAgent)?+(RegExp["\x246"]||RegExp["\x242"]):undefined;
(function(){var a=baidu.dom.ready=function(){var g=false,f=[],c;if(document.addEventListener){c=function(){document.removeEventListener("DOMContentLoaded",c,false);d()}}else{if(document.attachEvent){c=function(){if(document.readyState==="complete"){document.detachEvent("onreadystatechange",c);d()}}}}function d(){if(!d.isReady){d.isReady=true;for(var k=0,h=f.length;k<h;k++){f[k]()}}}function b(){try{document.documentElement.doScroll("left")}catch(h){setTimeout(b,1);return}d()}function e(){if(g){return}g=true;if(document.readyState==="complete"){d.isReady=true}else{if(document.addEventListener){document.addEventListener("DOMContentLoaded",c,false);window.addEventListener("load",d,false)}else{if(document.attachEvent){document.attachEvent("onreadystatechange",c);window.attachEvent("onload",d);var h=false;
try{h=window.frameElement==null}catch(i){}if(document.documentElement.doScroll&&h){b()}}}}}e();return function(h){d.isReady?h():f.push(h)}}();a.isReady=false})();baidu.event=baidu.event||{};baidu.event._listeners=baidu.event._listeners||[];baidu.lang=baidu.lang||{};baidu.lang.isString=function(a){return"[object String]"==Object.prototype.toString.call(a)};baidu.isString=baidu.lang.isString;baidu.dom._g=function(a){if(baidu.lang.isString(a)){return document.getElementById(a)}return a};baidu._g=baidu.dom._g;baidu.event.on=function(b,e,g){e=e.replace(/^on/i,"");b=baidu.dom._g(b);var f=function(i){g.call(b,i)},a=baidu.event._listeners,d=baidu.event._eventFilter,h,c=e;e=e.toLowerCase();if(d&&d[e]){h=d[e](b,e,f);c=h.type;f=h.listener}if(b.addEventListener){b.addEventListener(c,f,false)}else{if(b.attachEvent){b.attachEvent("on"+c,f)
}}a[a.length]=[b,e,g,f,c];return b};baidu.on=baidu.event.on;baidu.fn=baidu.fn||{};baidu.fn.bind=function(b,a){var c=arguments.length>2?[].slice.call(arguments,2):null;return function(){var e=baidu.lang.isString(b)?a[b]:b,d=(c)?c.concat([].slice.call(arguments,0)):arguments;return e.apply(a||e,d)}};baidu.browser.chrome=/chrome\/(\d+\.\d+)/i.test(navigator.userAgent)?+RegExp["\x241"]:undefined;baidu.fn.blank=function(){};baidu.dom.contains=function(a,b){var c=baidu.dom._g;a=c(a);b=c(b);return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};baidu.dom.hide=function(a){a=baidu.dom.g(a);a.style.display="none";return a};baidu.hide=baidu.dom.hide;baidu.dom.show=function(a){a=baidu.dom.g(a);a.style.display="";return a};baidu.show=baidu.dom.show;baidu.object=baidu.object||{};baidu.extend=baidu.object.extend=function(c,a){for(var b in a){if(a.hasOwnProperty(b)){c[b]=a[b]
}}return c};baidu.url=baidu.url||{};baidu.string.escapeReg=function(a){return String(a).replace(new RegExp("([.*+?^=!:\x24{}()|[\\]/\\\\])","g"),"\\\x241")};baidu.url.getQueryValue=function(b,c){var d=new RegExp("(^|&|\\?|#)"+baidu.string.escapeReg(c)+"=([^&#]*)(&|\x24|#)","");var a=b.match(d);if(a){return a[2]}return null};baidu.lang.isArray=function(a){return"[object Array]"==Object.prototype.toString.call(a)};baidu.lang.isFunction=function(a){return"[object Function]"==Object.prototype.toString.call(a)};baidu.lang.toArray=function(b){if(b===null||b===undefined){return[]}if(baidu.lang.isArray(b)){return b}if(typeof b.length!=="number"||typeof b==="string"||baidu.lang.isFunction(b)){return[b]}if(b.item){var a=b.length,c=new Array(a);while(a--){c[a]=b[a]}return c}return[].slice.call(b)};baidu.event.un=function(c,f,b){c=baidu.dom._g(c);
f=f.replace(/^on/i,"").toLowerCase();var i=baidu.event._listeners,d=i.length,e=!b,h,g,a;while(d--){h=i[d];if(h[1]===f&&h[0]===c&&(e||h[2]===b)){g=h[4];a=h[3];if(c.removeEventListener){c.removeEventListener(g,a,false)}else{if(c.detachEvent){c.detachEvent("on"+g,a)}}i.splice(d,1)}}return c};baidu.un=baidu.event.un;baidu.array=baidu.array||{};baidu.each=baidu.array.forEach=baidu.array.each=function(g,e,b){var d,f,c,a=g.length;if("function"==typeof e){for(c=0;c<a;c++){f=g[c];d=e.call(b||g,f,c);if(d===false){break}}}return g};baidu.dom.getDocument=function(a){a=baidu.dom.g(a);return a.nodeType==9?a:a.ownerDocument||a.document};baidu.dom.getComputedStyle=function(b,a){b=baidu.dom._g(b);var d=baidu.dom.getDocument(b),c;if(d.defaultView&&d.defaultView.getComputedStyle){c=d.defaultView.getComputedStyle(b,null);
if(c){return c[a]||c.getPropertyValue(a)}}return""};baidu.dom.getStyle=function(c,b){var e=baidu.dom;c=e.g(c);b=baidu.string.toCamelCase(b);var d=c.style[b]||(c.currentStyle?c.currentStyle[b]:"")||e.getComputedStyle(c,b);if(!d){var a=e._styleFixer[b];if(a){d=a.get?a.get(c):baidu.dom.getStyle(c,a)}}if(a=e._styleFilter){d=a.filter(b,d,"get")}return d};baidu.getStyle=baidu.dom.getStyle;baidu.event._eventFilter=baidu.event._eventFilter||{};baidu.event._eventFilter._crossElementBoundary=function(a,d){var c=d.relatedTarget,b=d.currentTarget;if(c===false||b==c||(c&&(c.prefix=="xul"||baidu.dom.contains(b,c)))){return}return a.call(b,d)};baidu.event._eventFilter.mouseenter=window.attachEvent?null:function(a,b,c){return{type:"mouseover",listener:baidu.fn.bind(baidu.event._eventFilter._crossElementBoundary,this,c)}
};baidu.event._eventFilter.mouseleave=window.attachEvent?null:function(a,b,c){return{type:"mouseout",listener:baidu.fn.bind(baidu.event._eventFilter._crossElementBoundary,this,c)}};; return baidu;})();var j=void 0,k=!0,l=null,m=!1,n={},ba="1",o="0",p=document,q=p.body,ca="CSS1Compat"!==p.compatMode,r=ca?q:p.documentElement,u=window.BAIDU_CLB_SLOTS_MAP,da=window.BAIDU_DAN_config||{},ea=100,ha=100,w=2147483647,ia=-2147483648,ja=Object.prototype.hasOwnProperty,x=o,ka="data-baidu-dan-id",B="data-baidu-dan-position-fix",la="data-baidu-dan-player-toggle-state",ma=0,na={N:"http://pplmauth.baidu.com/cpro/auth/authorizer.php",E:"http://epplmauth.baidu.com/cpro/auth/authorizer.php"};
na["gmvl.baidu.com"]=na.N;var C={N:"http://gmvl.baidu.com/dan/sp.html",E:"http://egmvl.baidu.com/dan/sp.html"};C["gmvl.baidu.com"]=C.N;
var oa="http://cpro.baidu.com/cpro/ui/y.js",pa="http://dn.baidu.com/images/logo_h.gif",qa="http://hong.baidu.com/",ra="0",sa="1",ta="2",Aa={close:{text:"\u5173\u95ed",width:16,height:16,offsetX:0,offsetY:0,T:"http://img.baidu.com/adm/control.gif",P:ua},minimize:{text:"\u6700\u5c0f\u5316",width:16,height:16,offsetX:-16,offsetY:0,T:"http://img.baidu.com/adm/control.gif",P:va}},Ba={"0":"video",1:"video",2:"barrier",3:"null",4:"static",5:"static",6:"video",7:"float",8:"null",20:"video",21:"video",22:"couplet",
23:"barrier",24:"static",25:"expand",26:"null",27:"captcha"},E={"0":"video",1:"video",2:"flash",3:"image",4:"null",5:"video",6:"video",7:"flash",8:"flash",20:"video",21:"flash",22:"image",23:"media"},F=l,Ca;function G(a,b,c){a.setAttribute(b,c)}var Da=m,H=p.createElement("div"),I=p.createElement("div");H.style.position="absolute";H.style.top="200px";I.style.position="fixed";I.style.top="100px";H.appendChild(I);q.appendChild(H);
I.getBoundingClientRect&&I.getBoundingClientRect().top==H.getBoundingClientRect().top&&(F={});q.removeChild(H);(function(){var a=p.createElement("object");"classid"in a&&(Da=k,a.setAttribute("test","test"),a.getAttribute("test")||(G=function(a,c,d){a[c]=d}))})();var Ea=p.createElement("div");Ea.innerHTML='<div style="opacity:.25;"></div>';Ca="0.25"==Ea.firstChild.style.opacity;function J(a){return j===a?"":encodeURIComponent(a)}
function K(a){var a=a&&a.style,b=0,c=0,d;if(F&&!ca&&(d=q.style.position||(q.currentStyle?q.currentStyle.position:""),"relative"===d||"absolute"===d))b=q.offsetLeft||0,c=q.offsetTop||0;a&&(a.top="0",a.left="0");return{width:r.clientWidth,height:r.clientHeight,scrollLeft:window.pageXOffset||r.scrollLeft,scrollTop:window.pageYOffset||r.scrollTop,f:b,l:c}}
function M(a){var b=new Image,c="baidu_dan_log_"+ +new Date;window[c]=b;b.onload=b.onerror=b.onabort=function(){try{delete window[c]}catch(a){window[c]=j}b=l};a+=-1<a.indexOf("?")?"&":"?";a+=".stamp="+Math.random();b.src=a}
function Fa(){var a=p.domain;0===a.indexOf("www.")&&(a=a.substr(4));"."===a.charAt(a.length-1)&&(a=a.substring(0,a.length-1));var b=a.match(RegExp("([a-z0-9][a-z0-9\\-]*?\\.(?:com|cn|net|org|gov|info|la|cc|co|jp|us|hk|tv|me|biz|in|be|io|tk|cm|li|ru|ws|hn|fm)(?:\\.(?:cn|jp|tw|ru))?)$","i"));return b?b[0]:a}function Ga(a){a=escape(a).replace(/([*+-.\/@_])/g,function(a){return"%"+a.charCodeAt(0).toString(16)});return a.replace(/%/g,"_")}
function Ha(a,b){var c=b||l,d=p.createElement("script");d.charset="utf-8";d.async=k;d.src=a;if(c){var e=m;d.onload=d.onreadystatechange=function(){if(!e&&(!d.readyState||"loaded"===d.readyState||"complete"===d.readyState))e=k,c()}}var f=p.getElementsByTagName("head")[0]||p.body;f.insertBefore(d,f.firstChild)}
function Ia(){var a=window.pageXOffset||r.scrollLeft,b=window.pageYOffset||r.scrollTop,c=p.createElement("div");baidu.dom.setStyles(c,{position:"absolute",top:"0px",left:"0px"});q.appendChild(c);var d=c.getBoundingClientRect(),e={};e.top=d.top+b;e.left=d.left+a;q.removeChild(c);return e}function Ja(a,b){var c=N(a);if(c.C&&(Ka(c),0<(O&292)))return;var d=c.type;n[d]&&n[d].create&&baidu.dom.ready(function(){n[d].create(c,b)});if(!c.placeholder&&b){var e=baidu.g(b);e&&e.parentNode.removeChild(e)}}
window.BAIDU_DAN_showAd=window.BAIDU_DAN_showAd||Ja;function La(a){a=N(a.id);a.la||(Ma(a),a.la=k);var b=a.type;("video"!==b||"video"!==a.a)&&Na(a);n[b]&&n[b].show&&n[b].show(a)}
n.video=function(){function a(a){z=a;s&&(y=(+new Date-s)/1E3)}function b(a){M(C[a.n]+"?"+a.d+"&tm="+J(+new Date)+"&l="+y+"&m="+e+"&alp="+f+"&alr="+g+"&alrs="+h+"&alm="+t+"&allc="+A+"&alsc="+i+"&als="+v+"&tgs="+x+"&pt="+a.c)}function c(c,e){b(c);switch(e){case "start":clearInterval(d);z||(d=setInterval(function(){a(m);150<y?clearInterval(d):b(c)},5E3));break;case "stop":clearInterval(d)}}var d=0,e=0,f=0,g=0,h=0,t=0,A=0,i=0,v=0,s=0,y=0,z=m;return{create:function(a){if(!(0<ma++)){var b=a.id,d=a.width,
c=a.height,e=Q(b,d,c),f=R(a,e);Oa(f,b,d,c);F&&G(e,B,2);q.appendChild(f);S(e,a);baidu.dom.setStyle(f,"z-index",ia)}},show:function(a){"video"===a.type&&"video"===a.a&&(s=+new Date,c(a,"start"));a=baidu.g(T(a.id));baidu.dom.setStyle(a,"z-index",w);F&&U()},D:function(b,d,f){"video"===f.type&&"video"===f.a&&(e++,z||(a(k),c(f,"stop")))},ja:function(){return y},va:function(d){z||(a(m),b(d))},wa:function(b){z||(a(k),c(b,"stop"))},ra:function(a){f++;b(a)},sa:function(a){g++;b(a)},ta:function(a){h++;b(a)},
qa:function(a){t++;b(a)},pa:function(a){A++;b(a)},oa:function(a){i++;b(a)},ua:function(a){v++;b(a)}}}();
n.barrier=function(){function a(a){c=setTimeout(function(){va(a)},a.X)}function b(){c&&clearTimeout(c)}var c=0;return{create:function(a){if(!(0<ma++)){var b=a.id,c=a.width,g=a.height,h=p.createElement("div"),t=Q(b,c,g),A=p.createElement("div"),i=p.createElement("ins");i.id="baidu_dan_collapsed_"+b;i.style.display="block";baidu.event.on(i,"mouseover",baidu.fn.bind(Pa,i,N(b)));var v=Qa(a,"close"),s=R(a,[h,A]);baidu.browser.chrome&&(s.style.overflow="visible");A.style.display="none";h.appendChild(t);
A.appendChild(v);A.appendChild(i);baidu.dom.setStyles(s,{width:c+"px",height:g+16+"px"});V(s,b,1,0,c,g+16);baidu.dom.setStyle(s,"z-index",ia);F&&G(h,B,1);F&&G(A,B,3);q.appendChild(s);S(t,a);b={src:a.ca,width:ea,height:ha};a=parseInt(a.da,10);(a=Ra[E[20>a?a+21:a]])&&a(i,b,baidu.fn.blank)}},show:function(b){var c=baidu.g(T(b.id));if(2>c.firstChild.children.length){var f=Qa(b,"minimize","close");c.firstChild.appendChild(f)}baidu.dom.setStyle(c,"z-index",w);F&&U();a(b)},ba:function(d,e,f){b();d=baidu.g(T(f.id));
d.style.height=N(d.getAttribute(ka)).height+16+"px";F||(e=d.style,e.bottom="auto",e.right="auto");V(d,j,1,0,f.width,f.height+16);c&&a(f)},D:function(a,b,c){a=baidu.g(T(c.id)).style;a.marginTop=0;a.marginLeft=0;a.height=ha+16+"px";a.top="auto";a.left="auto"},clear:b}}();n["static"]={create:function(a,b){var c=baidu.g(b);if(c){var d=Q(a.id,a.width,a.height),e=R(a,d);c.style.display="";c.appendChild(e);S(d,a);Ua(e,a)}},m:function(a){return{a:Va(E[u[a]._html.material_type]),placeholder:k}}};
n.couplet=function(){function a(a,f,g,h,t,A){var i=p.createElement("div"),v=p.createElement("div"),s=R({id:a,width:c,height:d},[i,v]);baidu.browser.chrome&&(s.style.overflow="visible");f=Q(a,f,g);g=p.createElement("div");g.id="baidu_dan_couplet_closeButton";baidu.on(g,"click",baidu.fn.bind(b,l,a,h));baidu.dom.setStyles(g,{position:"relative",left:"73px",top:"3px",width:"52px",height:"20px",cursor:"pointer",background:"url(http://dn.baidu.com/images/couplet.png) no-repeat 0px 0px"});baidu.dom.setStyles(i,
{border:"1px solid #cccccc",margin:"3px"});baidu.dom.setStyles(v,{height:"24px",borderTop:"1px solid #cccccc",background:"url(http://dn.baidu.com/images/couplet.png) repeat-x 0px -20px"});baidu.dom.setStyles(s,{border:"1px solid #cccccc",backgroundColor:"#f7f7f7",textAlign:"left",zIndex:ia});i.appendChild(f);v.appendChild(g);i=0;"right"===t&&(i=2);V(s,a,i,A,c,d);F&&G(v,B,5);q.appendChild(s);t="left"===t;S(f,{id:h.id,type:h.type,c:h.c,b:h.b,d:h.d,h:h.h,k:h.k,a:t?h.a:h.Ba,src:t?h.src:h.Aa,width:t?h.width:
h.$,height:t?h.height:h.Z});Ua(v,{id:a,type:h.type})}function b(a,b){ua({id:a,type:b.type})}var c=128,d=303;return{create:function(b){var c=screen.width;if(!(c<=b.minWidth||0<ma++)){var d=b.id,h=b.width,t=b.height,A="right_"+d,i=b.$,v=b.Z,s=b.ia,c=Math.floor((c-b.ea)/2)-h-10,c=0<=c&&1===s?c:10;a(d,h,t,b,"left",c);a(A,i,v,b,"right",c)}},show:function(a){var b=baidu.g(T(a.id)),a=baidu.g(T(a.id,"right"));b&&baidu.dom.setStyle(b,"z-index",w);a&&baidu.dom.setStyle(a,"z-index",w);F&&U()},m:function(a){var a=
u[a]._html,b=parseInt(a.content_width,10);if(!b||720>b)b=4095;return{a:Va(E[a.material_type]),ia:a.position,ea:b,minWidth:a.min_resolution,Aa:a.right_src,Ba:Va(E[a.right_type]),$:a.right_width,Z:a.right_height}}}}();
n.expand=function(){function a(a,b,c){var e,f,y=g[c.id];if(y.u){var z=r.clientWidth,ga=r.clientHeight;f=window.pageXOffset||r.scrollLeft;e=window.pageYOffset||r.scrollTop;var D=a.getBoundingClientRect();e=e+D.top-h.top;f=f+D.left-h.left;var D=a.getBoundingClientRect(),$=g[c.id],P=c.w-c.width,aa=c.o-c.height,L=g[c.id];L.t=L.L?D.top>ga-D.bottom?1:2:D.left>z-D.right?3:4;1===$.t&&(e-=aa);3===$.t&&(f-=P);baidu.dom.setStyles(b,{position:"absolute",top:e+"px",left:f+"px",width:c.w+"px",height:c.o+"px"});
baidu.dom.setStyle(a,"visibility","hidden");baidu.dom.setStyles(b,{visibility:"visible",zIndex:w});y.S=+new Date;y.p=1;d(c,2)}else y.r&&(y.log.R=+new Date-y.r,d(c,1))}function b(a,b,d){g[a.id].p&&(d=d.relatedTarget||d.toElement,(!d||!baidu.dom.contains(b,d))&&c(a))}function c(a){var b=g[a.id];if(b.p){b.I=+new Date;b.log.aa=b.I-b.S;b.p=0;var b=baidu.g(T(a.id)),c=baidu.g(T(a.id,"expand"));baidu.dom.setStyle(b,"visibility","visible");baidu.dom.setStyles(c,{visibility:"hidden",zIndex:ia});d(a,3)}}function d(a,
b){var c=g[a.id],d=[0,0,0,0,0,0,0,0];d[b]=1;switch(b){case 0:d[4]=c.log.M;d[5]=c.log.W;break;case 1:d[6]=c.log.R;break;case 3:d[7]=c.log.aa}Wa(a,0,1,"",d.join(","))}function e(a){a.id=a.id.replace("expand_","");var b=g[a.id];b.v=+new Date;b.log.M=b.v-b.O;b.log.W=b.v-b.r;b.u=1;d(a,0)}function f(a){var b=g[a.id];if(!b.options){var c=a.b;c&&(c=Xa(c,"e_1"));b.options={id:"expand_"+a.id,b:c,c:a.c,d:a.d,width:a.w,height:a.o,src:a.ga,a:a.ha,k:a.k,fn:"onExpandLoad",j:"id="+a.id}}return b.options}var g={},
h=Ia();return{create:function(d,e){var i=d.id;g[i]={L:1,t:1,Ca:0,r:0,O:0,v:0,ka:0,u:0,p:0,S:0,I:0,log:{M:0,W:0,R:0,aa:0}};i=g[i];d.height===d.o&&(i.L=0);n["static"].create(d,e);var i=f(d),h=Q(i.id,i.width,i.height),h=R(i,h);baidu.dom.setStyles(h,{width:"0px",height:"0px",position:"absolute",top:"0px",left:"0px",zIndex:w});Ua(h,i);q.appendChild(h);i=baidu.g(T(d.id));h=baidu.g(T(d.id,"expand"));baidu.event.on(i,"mouseenter",baidu.fn.bind(a,l,i,h,d));baidu.event.on(h,"mouseleave",baidu.fn.bind(c,l,d));
baidu.event.on(i,"mouseleave",baidu.fn.bind(b,l,d,h))},show:function(a){var b=g[a.id];b.r=+new Date;b.ka=1;setTimeout(function(){var c=f(a),d=baidu.g(Ya(c.id));b.O=+new Date;S(d,c,e)},5E3)},na:e,m:function(a){a=u[a]._html;return{a:Va(E[a.material_type]),ga:a.expand_src,ha:Va(E[a.expand_type]),w:a.expand_width,o:a.expand_height,placeholder:k}},Da:function(a,b){var c=a.id;g[c].u&&(c="expand_"+c);setTimeout(function(){var a=baidu.g(W("logo_"+c));a.width=b.width;a.height=b.height},0)}}}();
n.captcha=function(){function a(){if(wa)i();else{var a=N(P),b=baidu.g(T(a.id));"none"===b.style.display&&(V(b,a.id,1,0,xa,ya),F&&G(b.lastChild,B,1),e(a))}}function b(a){c(m);baidu.dom.hide(T(a.id))}function c(a){baidu.dom.setStyle(D,"display",a?"block":"none");baidu.dom.setStyles(ga,{"background-color":a?"#fef2f2":"","border-color":a?"#cc3333":"#cccccc"});baidu.dom.setStyle(z,"background-color",a?"#fef2f2":"")}function d(a){L=k;var b=t(a.id),d=baidu.g(z),e=encodeURIComponent(d.value);e?(Ha(na[a.n]+
"?"+("di="+a.id+"&ans="+e+"&jk="+b.xa+"&fn="+s+"&dt="+(+new Date-aa))),za=setTimeout(function(){L=m;clearTimeout(za);h(a.id,m)},5E3)):(c(k),baidu.on(d,"keydown",f))}function e(a){L=m;aa=+new Date;var a="captcha=1&"+a.ya,b={fn:y,dt:Math.round(+new Date/1E3)},c;for(c in b)ja.call(b,c)&&(a=a.replace(RegExp("&"+c+"=(\\w+)"),function(a,d){return a.replace(d,b[c])}));Ha("http://cb.baidu.com/ecom?"+a)}function f(){var a=baidu.g(z);baidu.un(a,"keydown",f);a.focus();a.value="";c(m)}function g(a){Sa[a.id]=
a;var a=t(a.id),b=N(a.id);if(Ta&&(Ta=m,a.s&&b.K&&b.J)){A();wa=k;return}if(wa)i();else{b=baidu.g(T(b.id));baidu.dom.show(b);F&&U();f();b=baidu.g(Ya(a.id));baidu.dom.setStyles(b,{width:a.width+"px",height:a.height+"px"});b.innerHTML="";S(b,a,baidu.fn.blank);Na(t(a.id));if(a.s){var c=a,d=document.createElement("div");baidu.dom.setStyles(d,{position:"absolute",left:"156px",bottom:"20px",width:"75px",height:"30px"});if(baidu.browser.ie&&8>parseInt(baidu.browser.ie,10))X(d,{id:c.id,width:"75",height:"30",
src:"http://dn.baidu.com/flash/captcha_vcode.swf",j:"img="+J(c.s)});else{var e=document.createElement("img");e.src="data:image/jpeg;base64,"+c.s;d.appendChild(e)}b.appendChild(d)}baidu.g($).innerHTML=a.za}}function h(a,d){if(L){var g=N(a),h=t(a);clearTimeout(za);if(d){if(baidu.g(z).value="",b(g),Ma(h),"undefined"!==typeof window[v])window[v](d)}else h=baidu.g(z),e(g),aa=(new Date).getTime(),c(k),baidu.on(h,"keydown",f)}}function t(a){a=Sa[a];return{id:a.id,width:a.width,height:a.height,c:a.product_type,
ma:a.material_type,a:E[a.material_type],src:a.src,h:a.monitor_url,za:unescape(a.question_tip),d:a.url_parameter,b:a.target_url,xa:a.qid,s:a.verification_code,n:a._vlog}}function A(){var a=N(P);window.fa&&(window.fa=l);Ha(oa,function(){window[sb]=window[v];var b={};b[a.K]={_html:"cpro_client=${cpro_client}|cpro_template=vcode_captchaF_254_218|cpro_h=185|cpro_w=250|cpro_at=image_flash|cpro_161=1|cpro_flush=4|cpro_cflush=#e10900|cpro_curl=#008000|cpro_cdesc=#444444|cpro_ctitle=#0000FF|cpro_cbg=#FFFFFF|cpro_cbd=#FFFFFF|cpro_cad=1".replace(/\$\{cpro_client\}/g,
a.J)};window[tb](b);i()})}function i(){var a=window[ub];a&&a()}var v="BAIDU_CLB_captchaVerifiedCallback",s="BAIDU_DAN_captchaAuthCallback",y="BAIDU_DAN_captchaMaterialCallback",z="baidu_dan_captcha_userInput",ga="baidu_dan_captcha_userInput_border",D="baidu_dan_captcha_errorInfo",$="baidu_dan_captcha_questionTip",P=m,aa=+new Date,L=m,za=0,Sa={},xa=330,ya=390;Ia();var Ta=k,wa=m,sb="fcallback_baiduCaptcha",ub="adDisplayHandler__baiduCaptcha",tb="BAIDU_CPRO_SETJSONADSLOT";window[y]=window[y]||g;window[s]=
window[s]||h;window.BAIDU_DAN_showCaptchaAd=window.BAIDU_DAN_showCaptchaAd||a;return{create:function(c){if(!P){P=c.id;var f=['<div style="position: absolute !important;width:'+xa+"px; height: "+ya+"px;overflow:hidden !important;background:url('http://dn.baidu.com/images/captcha.png') no-repeat scroll 0px 0px transparent; _filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, sizingMethod=none, src='http://dn.baidu.com/images/captcha.png');_background:none;\"></div>",'<div id="baidu_dan_captcha_innerWrapper" style="position:relative !important;text-align:left !important;width:310px;height:370px;top:10px;left:10px;font-size:12px;font-family: \'\u5b8b\u4f53,Arial\';"><div style="position: absolute ! important; right: 5px; top: 9px; height: 10px; width: 11px; cursor: pointer; " id="baidu_dan_captcha_closeButton"></div><div style="position: absolute ! important; left: 5px; top: 30px; width: 300px"><div id="baidu_dan_captcha_content" style="height: 250px; width: 300px;"></div><div style="height: 16px; margin-top: 10px; overflow: hidden; position: relative; width: 300px;">',
'<span id="'+$+'" style="line-height: 15px; color:#666666"></span>','<span style="line-height: 15px; color:#666666">\uff1a</span><span style="line-height: 15px; color:#666666; text-decoration:underline; cursor:pointer; margin-left:5px" id="baidu_dan_captcha_changeButton">\u6362\u4e00\u5f20</span></div><div style="overflow:hidden;*zoom:1;margin-top:9px;height:25px;vertical-align:middle;">','<div style="position:relative !important;float:left;height:23px;width:223px;border:1px solid #cccccc;" id="'+
ga+'">','<input type="text" style="margin-top:4px;padding:0px;line-height:16px;height:16px;margin-left:3px; border:0 none;width:218px;outline:none;" id="'+z+'">','<span style="position:absolute;line-height:16px;top:4px;right:0px;color:#cc3333;display:none" id="'+D+'">\u9519\u8bef\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165\uff01</span>','</div><div style="float:right;width:70px;height:25px;display:inline !important;cursor:pointer" id="baidu_dan_captcha_submit"></div></div><div style="height: 14px; line-height: 14px; margin-top: 8px; overflow: hidden;width: 300px;"><a style="color: #666666;" onfocus="this.blur()" href="mailto:yanzhengma@baidu.com" target="_blank">\u95ee\u9898\u53cd\u9988</a></div></div>'].join(""),
g=R(baidu.object.extend(c,{width:xa,height:ya}),[]);baidu.dom.setStyle(g,"display","none");g.innerHTML=f;q.appendChild(g);f=Q(c.id,c.width||0,c.height||0);baidu.g("baidu_dan_captcha_content").appendChild(f);Ua(baidu.g("baidu_dan_captcha_innerWrapper"),c);baidu.on("baidu_dan_captcha_submit","click",baidu.fn.bind(d,l,c));baidu.on("baidu_dan_captcha_closeButton","click",baidu.fn.bind(b,l,c));baidu.on("baidu_dan_captcha_changeButton","click",baidu.fn.bind(e,l,c));if(window.BAIDU_CLB_captchaBtnId&&baidu.g(window.BAIDU_CLB_captchaBtnId))baidu.on(window.BAIDU_CLB_captchaBtnId,
"click",function(){a()})}},m:function(a){a=u[a]._html;return{J:a.cpro_client,K:a.cpro_id}}}}();function ua(a){var b=baidu.g(T(a.id));n[a.type].clear&&n[a.type].clear();b.style.display="none";setTimeout(function(){b.parentNode.removeChild(b)},0);return m}function T(a,b){return b?"baidu_dan_wrapper_"+b+"_"+a:"baidu_dan_wrapper_"+a}function Ya(a){return"baidu_dan_container_"+a}function W(a){return"baidu_dan_player_"+a}
function Xa(a,b){var c=baidu.url.getQueryValue(a,"k");c?(b="&k="+Ga(c+"|"+b),a=a.replace("&k="+c,b)):a=-1===a.indexOf("?")?a+"?k="+Ga(b):a+"&k="+Ga(b);return a}function Q(a,b,c){var d=p.createElement("ins"),e=d.style;d.id=Ya(a);e.display="block";e.width=b+"px";e.height=c+"px";e.position="relative";e.overflow="hidden";return d}
function R(a,b){var b=baidu.lang.toArray(b),c=a.id,d=p.createElement("ins"),e=d.style,f=0,g=b.length;d.id=T(c);d.setAttribute(ka,c);d.setAttribute(la,o);e.display="block";e.overflow="hidden";e.position="relative";e.textDecoration="none";e.zIndex=w;e.width=a.width+"px";for(e.height=a.height+"px";f<g;f++)d.appendChild(b[f]);return d}function S(a,b,c){var d=Ra[b.a];d&&d.apply(l,arguments)}
function X(a,b){var c=b.j||"id="+J(b.id);b.z&&(c+="&rcv_url="+J(b.k));a.innerHTML=Da?'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" name="baidu_dan_player" '+(b.id?'id="'+W(b.id)+'" ':"")+'width="'+b.width+'" height="'+b.height+'" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0"><param name="allowScriptAccess" value="always" /><param name="quality" value="high" /><param name="wmode" value="transparent" /><param name="movie" value="'+b.src+
'" />'+(c?'<param name="flashvars" value="'+c+'" />':"")+"</object>":'<embed wmode="transparent" src="'+b.src+'" quality="high" name="baidu_dan_player" '+(b.id?'id="'+W(b.id)+'" ':"")+(c?'flashVars="'+c+'" ':"")+'width="'+b.width+'" height="'+b.height+'"allowScriptAccess="always" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />';!b.z&&b.b&&Za(a,b.b)}
function Za(a,b){if(b){var c=p.createElement("a"),d=c.style;c.href=b;c.target="_blank";d.position="absolute";d.zIndex=999;d.top=0;d.width="100%";d.height="2000px";d.backgroundColor="#fff";Ca?d.opacity=0:(d.filter="alpha(opacity=0)",d.zoom=1);"outline"in d?d.outline="none":c.hideFocus=k;a.insertBefore(c,a.firstChild)}}
function Qa(a,b){var c=1,d=arguments.length,e,f,g=p.createElement("div");g.className="baidu-dan-control-bar";for(g.style.overflow="hidden";c<d;c++)e=arguments[c],e=Aa[e],f=p.createElement("span"),f.innerHTML=e.text,baidu.dom.setStyles(f,{width:e.width+"px",height:e.height+"px",backgroundImage:"url("+e.T+")",backgroundPosition:e.offsetX+"px "+e.offsetY+"px",textIndent:"-2000px",overflow:"hidden",cssFloat:"right",styleFloat:"right"}),baidu.event.on(f,"click",baidu.fn.bind(e.P,f,a)),g.insertBefore(f,
g.firstChild);return g}
function Ua(a,b){var c;if("couplet"===b.type){c=document.createElement("a");c.id=T("logo_"+b.id);if(baidu.g(c.id))return;c.href=qa;c.target="_blank";var d={position:"absolute",zIndex:w,left:"5px",bottom:"3px",height:"17px",width:"12px",overflow:"hidden",background:"url("+pa+") no-repeat 0px 0px"},e=c.style;"outline"in e?e.outline="none":c.hideFocus=k;baidu.dom.setStyles(c,d)}else{c=document.createElement("div");c.id=T("logo_"+b.id);if(baidu.g(c.id))return;d={position:"absolute",zIndex:w,bottom:"0px",
height:"23px",right:"4px"};baidu.dom.setStyles(c,d);d="logo_"+b.id;X(c,{id:d,width:"18",height:"23",src:"http://dn.baidu.com/flash/logo_h.swf",j:(b.j||"id="+b.id)+"&logoId="+d})}a.appendChild(c)}
var Ra={video:function(a,b){X(a,{id:b.id,width:b.width,height:b.height,src:b.Y,j:["player_id="+J(b.id),"play_url="+J(b.src),"target_url="+J(b.b),"rcv_url="+J(b.k),"effect_time="+(b.X/1E3).toFixed(),"o_mute="+(da.videoMute?"1":"0"),"o_volume="+("number"==typeof da.videoVolume?da.videoVolume:"20")].join("&")})},flash:X,image:function(a,b,c){var d=p.createElement("img");d.width=b.width;d.height=b.height;d.src=b.src;"function"!==typeof c?d.complete?La(b):d.onload=function(){d.onload=l;La(b)}:c(b);d.style.display=
"block";a.appendChild(d);Za(a,b.b)},media:function(a,b){b.z=k;X(a,b)},shell:function(a,b){var c=b.src,d=b.fn||"onLoad",e=b.id,e=e.replace("expand_","");b.src="http://dn.baidu.com/flash/shell.swf";b.j=["id="+J(e),"fn="+J(d),"src="+J(c)].join("&");X(a,b)}};
function va(a){var b=baidu.g(T(a.id)),c=b.firstChild,d=b.lastChild,e=b.style;setTimeout(function(){e.width=ea+"px";e.height=ha+"px";x=ba;b.setAttribute(la,x);var f=n[a.type].D&&n[a.type].D(c,d,a);"barrier"===a.type?V(b,a.id,2,0,j,j):Oa(b,a.id);!f&&c!==d&&(c.style.display="none",d.style.display="block");a.C&&$a(a,"stop")},0);return m}
function Pa(a){var b=baidu.g(T(a.id)),c=b.style,d=a.height,e=b.firstChild,f=b.lastChild;c.width=a.width+"px";c.height=d+"px";x=o;b.setAttribute(la,x);if((!n[a.type].ba||!n[a.type].ba(e,f,a))&&e!==f)f.style.display="none",e.style.display="block";F&&(e.getAttribute(B)||delete F[a.id],U());return m}
var N=function(){var a={};return function(b,c){if(!a[b]){var d=c||u[b],e=d._html;a[b]={id:b,Fa:d._w,Ea:d._h,d:e.url_parameter,c:e.product_type,type:Ba[e.product_type],ma:e.material_type,a:E[e.material_type],src:e.src,width:parseInt(e.width,10),height:parseInt(e.height,10),Y:e.player_url||"http://img.baidu.com/adm/video-player.swf",da:e.collapse_type,ca:e.collapse_src||"http://img.baidu.com/adm/gm-logo-100x100.png",z:1==e.product_type||21==e.product_type,b:e.target_url,X:1E3*e.max_impression_time||
5E3,k:e.rcv_url,h:e.monitor_url,C:"video"===Ba[e.product_type],ya:e.query_string,n:d._vlog};d=a[b].type;n[d].m&&baidu.object.extend(a[b],n[d].m(b))}return a[b]}}(),ab={};function Va(a){return"flash"===a?"shell":a}
function V(a,b,c,d,e,f){var g=["left","center","right"];ab[b]={fixMode:c,marginOffset:d};e?baidu.dom.setStyles(a,{width:e+"px",height:f+"px"}):(e=a.offsetWidth,f=a.offsetHeight);F?(e=e||a.offsetWidth,g=f||a.offsetHeight,f=K(a),g={position:"absolute",top:f.scrollTop+(f.height-g)/2-f.l+"px"},0===c&&(g.left=f.scrollLeft-f.f+d+"px"),2===c&&(g.left=f.scrollLeft+f.width-f.f-e-d+"px"),1===c&&(g.left=f.scrollLeft-f.f+f.width/2+"px",g.marginLeft=(-(e/2)).toFixed()+"px"),baidu.dom.setStyles(a,g),b&&(F[b]=a)):
(b={position:"fixed",top:"50%",marginTop:(-(f/2)).toFixed()+"px"},1===c?(b.left="50%",b.marginLeft=(-(e/2)).toFixed()+"px"):b[g[c]]=d+"px",baidu.dom.setStyles(a,b))}function Oa(a,b,c,d){c?baidu.dom.setStyles(a,{width:c+"px",height:d+"px"}):(c=a.offsetWidth,d=a.offsetHeight);F?(bb(a,c,d),b&&(F[b]=a)):baidu.dom.setStyles(a,{position:"fixed",bottom:0,right:0})}
function bb(a,b,c){var b=b||a.offsetWidth,c=c||a.offsetHeight,d=K(a);baidu.dom.setStyles(a,{position:"absolute",left:d.scrollLeft+d.width-d.f-b+"px",top:d.scrollTop+d.height-d.l-c+"px"})}
var cb=[l,function(a,b,c){var b=b||a.offsetWidth,c=c||a.offsetHeight,d=K(a);baidu.dom.setStyles(a,{position:"absolute",left:d.scrollLeft-d.f+d.width/2+"px",top:d.scrollTop-d.l+d.height/2+"px",marginLeft:(-(b/2)).toFixed()+"px",marginTop:(-(c/2)).toFixed()+"px"})},bb,function(a,b,c){var b=b||a.offsetWidth,c=c||a.offsetHeight,d=K(a);baidu.dom.setStyles(a,{position:"absolute",left:d.scrollLeft+d.width-d.f-b+"px",top:d.scrollTop-d.l+(d.height-c)/2+"px"})},function(a,b,c){c=c||a.offsetHeight;b=K(a);baidu.dom.setStyles(a,
{position:"absolute",left:b.scrollLeft-b.f+"px",top:b.scrollTop-b.l+(b.height-c)/2+"px"})},function(a,b,c,d){V(a,d,ab[d].fixMode,ab[d].marginOffset)}];
function U(){var a,b,c=0,d;for(a in F)ja.call(F,a)&&(c++,b=F[a],d=b.lastChild.offsetWidth?b.lastChild:b.firstChild,(d=d.getAttribute(B))&&function(a,b,c){setTimeout(function(){cb[c](a,0,0,b)},0)}(b,a,d));0==c?(db=m,baidu.event.un(window,"scroll",U),baidu.event.un(window,"resize",U)):db||(db=k,baidu.event.on(window,"scroll",U),baidu.event.on(window,"resize",U))}var db=m;
function Ma(a){var b=Fa();baidu.lang.isArray(a.h)&&a.h.length&&baidu.array.each(a.h,function(a){a=a.replace(/\{placement\}/g,b);M(a)})}function Na(a){M(C[a.n]+"?"+a.d+"&tm="+J(+new Date)+"&pt="+J(a.c))}function Wa(a,b,c,d,e){a=N(a.id);M(C[a.n]+"?"+a.d+"&tm="+J(+new Date)+"&pt="+J(a.c)+"&ac="+(b+"|"+c+"|"+d+"|"+e))}function Y(a,b){var c=baidu.g(T(a)),d=Y[b];c&&d&&(c=Array.prototype.slice.call(arguments),c[0]=N(a),c.splice(1,1),d.apply(l,c))}
window.BAIDU_DAN_materialCallback=window.BAIDU_DAN_materialCallback||Y;Y.onMinimize=va;Y.onRestore=Pa;Y.onClose=function(a){ua(a)};Y.onLoad=function(a){a.C&&$a(a,"start");La(a)};Y.onExpandLoad=n.expand.na;Y.onFinish=n.video.va;Y.onPause=n.video.wa;Y.logMousePause=n.video.ra;Y.logMouseReplay=n.video.sa;Y.logMouseRestore=n.video.ta;Y.logMouseMute=n.video.qa;Y.logMouseMinimize=n.video.pa;Y.logMouseClose=n.video.oa;Y.logMouseSearch=n.video.ua;
Y.openWindow=function(a,b){b&&b.url?window.open(b.url):Y.openClickUrl(a,{Ga:0})};Y.openClickUrl=function(a,b){if(a.b){var c=0,d=a.b;baidu.url.getQueryValue(d,"k");b&&1===b.valid&&(c=1);d=Xa(d,"v_"+c);b&&b.inField&&(d+="&in="+J(b.inField));window.open(d)}};Y.sendInteractiveLog=function(a,b){for(var c=b.name,d=0;d<c.length;d++)c[d]=J(c[d]);Wa(a,1,b.online,c.join(","),b.value.join(","))};
Y.exposeAdElements=function(a){var b=baidu.g(T(a.id)),a=baidu.g(W(a.id));window.BAIDU_DAN_adElements={ins:b.firstChild,wrapper:b,swf:a}};Y.resizeLogo=function(a,b){setTimeout(function(){var a=baidu.g(W(b.logoId));a.width=b.width;a.height=b.height},0)};var Z=0,eb=0,fb=0,O=0,gb=0,hb=0,ib=0,jb=0;function $a(a,b){clearInterval(ib);"start"===b&&0>=jb&&(kb(a),ib=setInterval(function(){kb(a)},8E3))}
function kb(a){10<=jb++?clearInterval(ib):(lb(a,mb,function(a){a===m&&clearInterval(ib)}),M("http://cbjslog.baidu.com/dan_log?"+["ty="+ra,"di="+a.id,a.d,"pt="+a.c,"tgs="+x,"l="+n.video.ja(),"c="+Z,"x="+eb,"y="+fb,"q="+(ca?1:0),"tm="+ +new Date].join("&")))}var mb=[nb,ob,pb,qb,rb];function nb(a){var b=baidu.g(T(a.id)),c=baidu.g(Ya(a.id)),a=baidu.g(W(a.id));return!b||!c||!a?(Z|=1,m):k}function ob(a){if(x===o){var b=baidu.g(W(a.id)),a=vb(a,b);a.A&&(eb=a.F,Z|=2);a.B&&(fb=a.H,Z|=4);a.V||(Z|=8)}}
function pb(a){var b=baidu.g(T(a.id)),c=baidu.g(Ya(a.id)),d=baidu.g(W(a.id)),e;if(x===o)for(var c=[b,c,d],d=0,f=c.length;d<f;d++)if(e=c[d],b=e.offsetWidth||e.clientWidth,e=e.offsetHeight||e.clientHeight,b!=a.width||e!=a.height){Z|=16;break}}function qb(a){for(var b=baidu.g(W(a.id)),a=baidu.g(T(a.id));;b=b.parentNode){if(!wb(b)){Z|=32;break}if(b===a)break}}
function rb(a){var b=baidu.g(W(a.id)),a="video"===a.a?a.Y:a.src;if(Da)for(var c,d=0;d<b.childNodes.length;d++){if(c=b.childNodes[d],"movie"===c.getAttribute("name")&&c.getAttribute("value")!=a){Z|=64;break}}else b.getAttribute("src")!=a&&(Z|=64)}
function vb(a,b){if(b.getBoundingClientRect){var c=b.getBoundingClientRect(),d=b.ownerDocument,d="CSS1Compat"!==d.compatMode?d.body:d.documentElement,e=d.clientLeft,f=d.clientTop,g=c.right-d.clientWidth-e,h=c.bottom-d.clientHeight-f;return{A:1<Math.abs(g),B:1<Math.abs(h),F:g,H:h,V:c.left>=e&&c.top>=d.clientTop&&1>=g&&1>=h,U:c.right-e>=a.width&&c.bottom-f>=a.height&&1>=g&&1>=h}}M("http://cbjslog.baidu.com/dan_log?"+["ty="+ta,"url="+J(p.URL)].join("&"));return{A:m,B:m,F:0,H:0,V:k,U:k}}
function wb(a){var b=baidu.dom.getStyle,c;if(!(c="none"==b(a,"display"))){if(!(b="hidden"==b(a,"visibility")))a=Ca?baidu.dom.getStyle(a,"opacity")||"1":(a=a.style.filter)&&0<=a.indexOf("opacity")?parseFloat(a.match(/opacity[=:]([^)]*)/)[1])/100+"":"1",b="1"!=a;c=b}return c?m:k}function lb(a,b,c){for(var d=k,e=0,f=b.length;e<f;e++)if(b[e]&&"function"===typeof b[e]&&b[e](a)===m){d=m;break}c&&c(d)}
function Ka(a){lb(a,xb);M("http://cbjslog.baidu.com/dan_log?"+["ty="+sa,"di="+a.id,a.d,"pt="+a.c,"if="+O,"x="+gb,"y="+hb,"ib="+(0<(O&292)?1:0),"ir="+J(yb()),"tm="+ +new Date].join("&"))}var xb=[zb,Ab,Bb,Cb,Db];function zb(){return Eb()?(O|=1,k):m}
function Bb(a){for(var b=Fb(),c=window.top,d,e,f=0,g=b.length;f<g;f++){d=b[f];if(d===c)break;d=d.document;e=(e="CSS1Compat"!==d.compatMode)?d.body:d.documentElement;d=e.clientWidth;e=e.clientHeight;if(d<a.width||e<a.height)O|=4;d>2*a.width&&e>2*a.height&&(O|=8);100<d&&100<e&&(O|=16);if(28===(O&28))break}}function Ab(){Gb()!=window.top&&(O|=2)}function Cb(){for(var a=Fb(),b,c=0,d=a.length-1;c<d;c++)if(b=a[c],!wb(b.frameElement)){O|=32;break}}
function Db(a){var b=Fb();2>b.length||(a=vb(a,b[0].frameElement),a.A&&(gb=a.F,O|=64),a.B&&(hb=a.H,O|=128),a.U||(O|=256))}function Eb(){return window!=window.top&&window!=window.parent?k:m}function Fb(){for(var a=0,b=window,c=b.top,d=[b];b!==c&&10>a++&&Hb(b)&&Hb(b.parent);){b=b.parent;d.push(b)}Fb=function(){return d};return d}function Gb(){var a=Fb();return a[a.length-1]}function Hb(a){var b=m;try{a&&"object"===typeof a&&a.document&&"setInterval"in a&&(b=k)}catch(c){b=m}return b}
function yb(){if(!Eb())return"";var a=Gb();return a===window.top?a.document.location.href:a.document.referrer||a.document.location.href}var Ib=window.BAIDU_DAN_readySlotId;if(Ib){Ja(Ib,"");0.01>Math.random()&&M("http://cbjslog.baidu.com/dan_log?"+["ty=4","di="+Ib,"url="+J(p.URL)].join("&"));try{delete window.BAIDU_DAN_readySlotId}catch(Jb){window.BAIDU_DAN_readySlotId=j}};})();