/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2013-05-29 07:50:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gbk\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/dwr/engine.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/dwr/util.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/dwr/interface/searchService.js\"></script>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\r\n");
      out.write("var _id = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\r\n");
      out.write("searchService.getSearchResultById(_id, fillDetailResult);\r\n");
      out.write("\r\n");
      out.write("function fillDetailResult(record)\r\n");
      out.write("{\r\n");
      out.write("\tvar image = document.getElementById(\"image\");\r\n");
      out.write("\timage.innerHTML+=\"<table><tr><td><img src='../showpic?id=\"+record.imageUrl+\"'></td>\" + \r\n");
      out.write("                   \"<td>\"\r\n");
      out.write("\t\t\t\t   + \"<table><tr><td>\" + record.name + \"</td></tr></table>\"\r\n");
      out.write("                   +\"</td></tr></table>\";\r\n");
      out.write("\r\n");
      out.write("\tvar contentdiv = document.getElementById(\"detail\");\r\n");
      out.write("\tvar table;\r\n");
      out.write("\r\n");
      out.write("\tvar content = record.content;\r\n");
      out.write("\tvar lines = content.split(\"\\r\\n\");\r\n");
      out.write("\r\n");
      out.write("\tif (lines.length > 0) {\r\n");
      out.write("\t\ttable = document.createElement('table');\r\n");
      out.write("\t\ttable.setAttribute(\"border\",\"1\");\r\n");
      out.write("\t\tcontentdiv.appendChild(table);\r\n");
      out.write("\t}\r\n");
      out.write("\telse {\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i=0;i<lines.length;i++){\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar tr = document.createElement('tr');\r\n");
      out.write("\t\ttr.setAttribute('bgcolor','#eeeeee');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar td1;\r\n");
      out.write("\t\tvar td2;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar line = lines[i];\r\n");
      out.write("\r\n");
      out.write("\t\tvar data1 = line.substring(0, line.indexOf(\":\"));\r\n");
      out.write("\t\tvar data2 = line.substring(line.indexOf(\":\") + 1);\r\n");
      out.write("\r\n");
      out.write("\t\ttd1 = document.createElement('td');\r\n");
      out.write("\t\ttd1.innerHTML = \"<font size=2px>\" + data1 + \"</font>\";\r\n");
      out.write("\t\ttr.appendChild(td1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\ttd2 = document.createElement('td');\r\n");
      out.write("\t\ttd2.innerHTML = \"<font size=2px>\" + data2 + \"</font>\";\r\n");
      out.write("\t\ttr.appendChild(td2);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\ttable.appendChild(tr);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tcontentdiv.innerHTML = contentdiv.innerHTML;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar original = document.getElementById(\"original\");\r\n");
      out.write("\toriginal.innerHTML = \"<a href='\" + record.url + \"' target='_blank'>\" + record.url + \"</a>\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- è¿æ¯ç¨äºæ¾ç¤ºå¾ççä½ç½® -->\r\n");
      out.write("<div id=\"image\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- ç¨äºæ¾ç¤ºåURL -->\r\n");
      out.write("<div id=\"original\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- è¿æ¯ç¨äºæ¾ç¤ºè¯¦ç»ä¿¡æ¯çä½ç½® -->\r\n");
      out.write("<div id=\"detail\" >\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
